config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :apartments
  end

  resources :apartments do
    resources :invoices, only: [:index, :show]
  end
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :user
  has_many :invoices
  has_many :cleaning_invoices, through: :invoices
end

app/models/cleaning_invoice.rb
class CleaningInvoice < ActiveRecord::Base
  belongs_to :invoice
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :apartment
  has_many :cleaning_invoices
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  extend Enumerize

  enumerize :role, in: [:owner, :cleaner, :manager, :admin], default: :owner

  has_many :apartments
  has_many :invoices, through: :apartments
  has_many :cleaning_invoices, through: :invoices, source: :apartments
end

app/controllers/apartments_controller.rb
  class ApartmentsController < ApplicationController
  before_action :set_user

  def index
    @apartments = @user.apartments
  end

  def show

  end

  def new
    @apartment = Apartment.new
  end

  def create
    @apartment = Apartment.new(apartment_params)

    if @apartment.valid?
      @apartment.save
      redirect_to user_apartments_path(current_user)
    else
      render "new"
    end
  end




  private

  def apartment_params
    params.require(:apartment).permit(:street, :user_id, :house_number, :state)
  end

  def set_user
    @user = User.find(current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_user!, unless: :pages_controller?

  # Uncomment these lines to get pundit
  # include Pundit
  # after_action :verify_authorized, except:  :index, unless: :devise_or_pages_or_admin_controller?
  # after_action :verify_policy_scoped, only: :index, unless: :devise_or_pages_or_admin_controller?
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def devise_or_pages_or_admin_controller?
    devise_controller? || pages_controller? || params[:controller] =~ /^admin/
  end

  def pages_controller?
    controller_name == "pages"  # Brought by the `high_voltage` gem
  end

  def user_not_authorized
    flash[:error] = I18n.t('controllers.application.user_not_authorized', default: "You can't access this page.")
    redirect_to(root_path)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController

  before_action :set_apartment

  def index

  end

  private
  def invoice_params
    params.require(:invoices).permit(:apartment_id)
  end


  def set_apartment
    @apartment = Apartment.find(params[:id])
  end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/apartments/index.html.slim
div class="text-center"
  .panel.panel-default
    .panel-heading
      h2 Casas
    .panel-body
      p You have #{@apartments.size} apartments in Amsterdam.

    table.table
      thead
        tr
          th #
          th street
          th house number
          th etc
          th invoices
      - @apartments.each do |apartment|
        tbody
          tr
            th scope="row" = apartment.id
            td = apartment.street
            td = apartment.house_number
            td = apartment.state
            td = link_to "invoices", apartment_invoices_path(apartment.id)

  |

= link_to "Add apartment", new_user_apartment_path(current_user), {class: "btn btn-primary"}

app/views/apartments/new.html.slim
.text-center
.container
  .row
    .col-sm-4.col-sm-offset-4
      = simple_form_for([@user, @apartment]) do |f|
        = f.error_notification
        = f.input :user_id, input_html: { value: current_user.id}, as: :hidden
        = f.input :street, :input_html => {:size => 40, :maxlength => 27}, placeholder: 'street', label: false
        = f.input :house_number, :input_html => {:size => 40, :maxlength => 27}, placeholder: 'house number', label: false
        = f.input :state, :input_html => {:size => 40, :maxlength => 27}, placeholder: 'state', label: false



        = f.button :submit, class: 'btn btn-primary', value: 'Add apartment'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title).presence || "Wagon Rails" %></title>
  <meta name="description" content="<%= (yield(:description).presence || "").squish %>">

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/flashes" %>
  <%= render "shared/navbar" %>

  <%= yield %>

  <%= javascript_include_tag :application %>
  <%= yield(:after_js) %>

</body>
</html>

app/views/pages/home.html.slim
h1 Welcome to Facili Huis

- if user_signed_in?
  = link_to "All apartments", user_apartments_path(current_user), {class: "btn btn-primary"}

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.slim
.navbar-wagon
  /! Logo
  = link_to root_path, class: "navbar-wagon-brand" do
    = image_tag "logo.png"

  .navbar-wagon-item
    .dropdown
      i.fa.fa-bars.dropdown-toggle data-toggle="dropdown"
      ul.dropdown-menu.dropdown-menu-right.navbar-wagon-dropdown-menu
        - if user_signed_in?
          li
            = link_to "#" do
              i.fa.fa-user
              = t ".profile", default: "Profile"
          li
            = link_to "#" do
              i.fa.fa-home
              = t ".profile", default: "Home"
          li
            = link_to destroy_user_session_path, method: :delete do
              i.fa.fa-sign-out
              = t ".sign_out", default: "Log out"
        - else
          li
            = link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"